title: CHROMEBOOK DOCS
description: Documentaccon de chroembooks
theme: just-the-docs

url: https://vadik317.github.io/chromebook-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
